# Generated by Django 5.1.15 on 2026-03-05 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketSortPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_id', models.CharField(help_text='S1-S32', max_length=4, unique=True)),
                ('phrase_text', models.CharField(max_length=200)),
                ('expected_bucket', models.CharField(choices=[('purpose', 'Organizational purpose'), ('good_employer', 'Good employer'), ('compensation', 'Compensation & benefits'), ('job_tasks', 'Job tasks')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6)),
                ('boundary_pair', models.CharField(blank=True, help_text="e.g. 'purpose/good_employer'", max_length=40)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['phrase_id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_code', models.CharField(blank=True, help_text='Auto-generated anonymous ID (e.g. P0001)', max_length=16, unique=True)),
                ('prolific_id', models.CharField(blank=True, db_index=True, help_text='Prolific PID from URL params', max_length=64)),
                ('study_assignment', models.CharField(choices=[('study2', 'Study 2 — Job Seeker'), ('study3', 'Study 3 — Hiring Manager')], max_length=6)),
                ('wage_arm', models.CharField(choices=[('A', 'Arm A — Wages Visible'), ('B', 'Arm B — Wages Hidden')], max_length=1)),
                ('occupation_pool', models.CharField(blank=True, choices=[('business_analyst', 'Business Analyst'), ('financial_analyst', 'Financial Analyst'), ('marketing_analyst', 'Marketing Analyst')], help_text='Which occupation pool this participant sees', max_length=20)),
                ('wage_counterbalance', models.CharField(blank=True, help_text='Signal types assigned high wages (comma-separated)', max_length=60)),
                ('status', models.CharField(choices=[('created', 'Created'), ('consented', 'Consented'), ('reading', 'Reading Postings'), ('stage1', 'Stage 1 — Rankings'), ('stage2', 'Stage 2 — Card Sort'), ('stage3', 'Stage 3 — Competition'), ('stage4', 'Stage 4 — Bucket Sort'), ('individual_diffs', 'Individual Differences'), ('demographics', 'Demographics'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='created', max_length=20)),
                ('consented', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('posting_order_seed', models.IntegerField(blank=True, null=True)),
                ('attention_checks_passed', models.IntegerField(default=0)),
                ('attention_checks_failed', models.IntegerField(default=0)),
                ('flagged_for_exclusion', models.BooleanField(default=False)),
                ('completion_code', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='core_partic_status_12c028_idx'), models.Index(fields=['study_assignment', 'wage_arm'], name='core_partic_study_a_d33385_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndividualDifferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsv_salary', models.IntegerField(blank=True, null=True)),
                ('jsv_benefits', models.IntegerField(blank=True, null=True)),
                ('jsv_mission', models.IntegerField(blank=True, null=True)),
                ('jsv_worklife', models.IntegerField(blank=True, null=True)),
                ('jsv_growth', models.IntegerField(blank=True, null=True)),
                ('jsv_security', models.IntegerField(blank=True, null=True)),
                ('jsv_impact', models.IntegerField(blank=True, null=True)),
                ('jsv_autonomy', models.IntegerField(blank=True, null=True)),
                ('jsv_coworkers', models.IntegerField(blank=True, null=True)),
                ('jsv_reputation', models.IntegerField(blank=True, null=True)),
                ('csr_responsibility', models.IntegerField(blank=True, null=True)),
                ('csr_lower_salary', models.IntegerField(blank=True, null=True)),
                ('csr_usually_mean_it', models.IntegerField(blank=True, help_text='Reverse-scored', null=True)),
                ('csr_pay_attention', models.IntegerField(blank=True, null=True)),
                ('skep_improve_image', models.IntegerField(blank=True, null=True)),
                ('skep_grain_of_salt', models.IntegerField(blank=True, null=True)),
                ('skep_genuinely_motivated', models.IntegerField(blank=True, help_text='Reverse-coded', null=True)),
                ('political_orientation', models.IntegerField(blank=True, help_text='1=Very liberal, 7=Very conservative, null=Prefer not to say', null=True)),
                ('household_income', models.CharField(blank=True, max_length=50)),
                ('job_search_urgency', models.IntegerField(blank=True, help_text='1-7', null=True)),
                ('job_satisfaction', models.IntegerField(blank=True, help_text='1-7', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_differences', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('gender_self_describe', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('employment_other', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('industry_other', models.CharField(blank=True, max_length=200)),
                ('work_experience_years', models.IntegerField(blank=True, null=True)),
                ('last_job_search', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='core.participant')),
            ],
            options={
                'verbose_name_plural': 'Demographics',
            },
        ),
        migrations.CreateModel(
            name='BucketSortResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1, help_text='1st, 2nd, 3rd appearance')),
                ('bucket_assigned', models.CharField(blank=True, help_text='Which bucket (empty if missed)', max_length=20)),
                ('was_missed', models.BooleanField(default=False)),
                ('time_on_phrase_ms', models.IntegerField(blank=True, help_text='ms from appearance to catch', null=True)),
                ('game_elapsed_ms', models.IntegerField(blank=True, help_text='ms since game start', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.bucketsortphrase')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_sort_responses', to='core.participant')),
            ],
            options={
                'ordering': ['participant', 'game_elapsed_ms'],
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_pool', models.CharField(choices=[('business_analyst', 'Business Analyst'), ('financial_analyst', 'Financial Analyst'), ('marketing_analyst', 'Marketing Analyst')], help_text='Which occupation pool this posting belongs to', max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('signal_type', models.CharField(choices=[('purpose_innovation', 'Purpose — Innovation'), ('purpose_social', 'Purpose — Social'), ('good_employer', 'Good Employer'), ('neutral', 'Neutral')], max_length=20)),
                ('salary_high_text', models.CharField(help_text='Salary text when assigned high wages', max_length=50)),
                ('salary_high_low', models.IntegerField(help_text='Min of high salary range')),
                ('salary_high_high', models.IntegerField(help_text='Max of high salary range')),
                ('salary_low_text', models.CharField(help_text='Salary text when assigned low wages', max_length=50)),
                ('salary_low_low', models.IntegerField(help_text='Min of low salary range')),
                ('salary_low_high', models.IntegerField(help_text='Max of low salary range')),
                ('company_intro', models.TextField(help_text='Neutral company description paragraph')),
                ('role_description', models.TextField(help_text="'The Role' section text")),
                ('signal_section_title', models.CharField(help_text="e.g. 'Who We Are', 'Our Mission', 'Working at Crestline'", max_length=50)),
                ('signal_section_text', models.TextField(help_text='The framing paragraph (purpose/good-employer/neutral)')),
                ('requirements_text', models.TextField()),
            ],
            options={
                'ordering': ['occupation_pool', 'signal_type'],
                'unique_together': {('occupation_pool', 'signal_type')},
            },
        ),
        migrations.CreateModel(
            name='BucketSortReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_bucket', models.CharField(max_length=20)),
                ('second_bucket', models.CharField(max_length=20)),
                ('resolution', models.CharField(choices=[('mistake', 'It was a mistake'), ('fits_both', 'It fits both categories')], max_length=10)),
                ('final_bucket', models.CharField(blank=True, help_text='If mistake, which bucket is correct', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.bucketsortphrase')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_reconciliations', to='core.participant')),
            ],
            options={
                'unique_together': {('participant', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='RankingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('perceived_pay', 'Perceived Pay'), ('employer_quality', 'Employer Quality'), ('challenging_rewarding', 'Challenging & Rewarding Work'), ('workplace_culture', 'Workplace Culture'), ('belief_alignment', 'Belief-Work Alignment'), ('mission_identity', 'Mission/Identity Clarity'), ('overall_desirability', 'Overall Desirability')], max_length=25)),
                ('dimension_order', models.IntegerField(help_text='Presentation order (1-7)')),
                ('ranking_order', models.JSONField(help_text="List of signal_types in rank order, e.g. ['purpose_innovation','neutral',...]")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_responses', to='core.participant')),
            ],
            options={
                'ordering': ['participant', 'dimension_order'],
                'unique_together': {('participant', 'dimension')},
            },
        ),
    ]
