# Generated by Django 5.1.15 on 2026-03-02 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_label', models.CharField(help_text='A-F condition label from IRB design matrix', max_length=1)),
                ('company_name', models.CharField(max_length=100)),
                ('company_tagline', models.CharField(blank=True, help_text='Italicized subtitle under company name', max_length=200)),
                ('framing', models.CharField(choices=[('purpose', 'Purpose / Mission-driven'), ('good_employer', 'Good Employer'), ('neutral', 'Neutral / Control')], max_length=15)),
                ('salary_level', models.CharField(choices=[('high', 'High ($78,000)'), ('low', 'Low ($52,000)')], max_length=4)),
                ('salary_amount', models.IntegerField(help_text='Annual salary in dollars')),
                ('job_title', models.CharField(default='Marketing Analyst', max_length=100)),
                ('location', models.CharField(default='Washington, DC metro area', max_length=100)),
                ('responsibilities', models.JSONField(default=list, help_text='List of responsibility bullet points')),
                ('company_description', models.TextField(help_text='The framing paragraph (purpose/good-employer/neutral)')),
                ('benefits_text', models.TextField(help_text='Benefits line')),
            ],
            options={
                'ordering': ['condition_label'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_text', models.TextField(help_text='The bolded phrase shown to participant')),
                ('context_text', models.TextField(help_text='1-2 sentence job posting context')),
                ('item_type', models.CharField(choices=[('main', 'Main Item'), ('practice', 'Practice Item'), ('attention', 'Attention Check')], default='main', max_length=10)),
                ('dict_category', models.CharField(blank=True, max_length=64)),
                ('dict_subcategory', models.CharField(blank=True, max_length=128)),
                ('irb_category', models.CharField(blank=True, help_text='Expected correct IRB category', max_length=32)),
                ('correct_categories', models.JSONField(blank=True, default=list, help_text='List of correct category slugs')),
                ('feedback_text', models.TextField(blank=True, help_text='Feedback shown after practice items')),
                ('is_active', models.BooleanField(default=True)),
                ('is_ambiguous', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0, help_text='Order within practice/attention sets')),
            ],
            options={
                'ordering': ['item_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_code', models.CharField(help_text='Auto-generated anonymous ID (e.g. P0001)', max_length=16, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Optional external ID (for future Prolific integration)', max_length=64)),
                ('session_type', models.CharField(choices=[('study1', 'Study 1 Only'), ('study2', 'Study 2 Only'), ('combined', 'Combined Session')], max_length=10)),
                ('status', models.CharField(choices=[('consented', 'Consented'), ('in_study1', 'In Study 1'), ('in_study2', 'In Study 2'), ('in_demographics', 'In Demographics'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='consented', max_length=20)),
                ('consented', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('phrase_seed', models.IntegerField(blank=True, null=True)),
                ('posting_order_seed', models.IntegerField(blank=True, null=True)),
                ('attention_checks_passed', models.IntegerField(default=0)),
                ('attention_checks_failed', models.IntegerField(default=0)),
                ('flagged_for_exclusion', models.BooleanField(default=False)),
                ('completion_code', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='core_partic_status_12c028_idx'), models.Index(fields=['started_at'], name='core_partic_started_130b11_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndividualDifferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsv_salary', models.IntegerField(blank=True, null=True)),
                ('jsv_benefits', models.IntegerField(blank=True, null=True)),
                ('jsv_mission', models.IntegerField(blank=True, null=True)),
                ('jsv_worklife', models.IntegerField(blank=True, null=True)),
                ('jsv_growth', models.IntegerField(blank=True, null=True)),
                ('jsv_security', models.IntegerField(blank=True, null=True)),
                ('jsv_impact', models.IntegerField(blank=True, null=True)),
                ('jsv_autonomy', models.IntegerField(blank=True, null=True)),
                ('jsv_coworkers', models.IntegerField(blank=True, null=True)),
                ('jsv_reputation', models.IntegerField(blank=True, null=True)),
                ('csr_responsibility', models.IntegerField(blank=True, null=True)),
                ('csr_lower_salary', models.IntegerField(blank=True, null=True)),
                ('csr_usually_mean_it', models.IntegerField(blank=True, help_text='Reverse-scored', null=True)),
                ('csr_pay_attention', models.IntegerField(blank=True, null=True)),
                ('skep_improve_image', models.IntegerField(blank=True, null=True)),
                ('skep_grain_of_salt', models.IntegerField(blank=True, null=True)),
                ('skep_genuinely_motivated', models.IntegerField(blank=True, help_text='Reverse-coded', null=True)),
                ('political_orientation', models.IntegerField(blank=True, help_text='1=Very liberal, 7=Very conservative, null=Prefer not to say', null=True)),
                ('household_income', models.CharField(blank=True, max_length=50)),
                ('job_search_urgency', models.IntegerField(blank=True, help_text='1-7', null=True)),
                ('job_satisfaction', models.IntegerField(blank=True, help_text='1-7', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_differences', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('gender_self_describe', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('employment_other', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('industry_other', models.CharField(blank=True, max_length=200)),
                ('work_experience_years', models.IntegerField(blank=True, null=True)),
                ('last_job_search', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='core.participant')),
            ],
            options={
                'verbose_name_plural': 'Demographics',
            },
        ),
        migrations.CreateModel(
            name='Study1PostTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(help_text='1-7: How confident in classifications')),
                ('confusion_text', models.TextField(blank=True, help_text='Open text: categories confusing or hard to tell apart')),
                ('familiarity', models.IntegerField(help_text='1-7: How familiar with reading job postings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study1_post_task', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Study2ManipulationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_mission', models.CharField(max_length=100)),
                ('most_workplace', models.CharField(max_length=100)),
                ('highest_salary', models.CharField(max_length=100)),
                ('job_title_check', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_checks', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Study2PostRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_company', models.CharField(help_text='Auto-filled from attractiveness rank #1', max_length=100)),
                ('explanation_text', models.TextField(blank=True, help_text='Why this posting stood out')),
                ('min_acceptable_salary', models.IntegerField(blank=True, help_text='Minimum salary to accept at top-ranked company', null=True)),
                ('po_fit_values', models.IntegerField(blank=True, help_text='1-7: Personal values aligned', null=True)),
                ('po_fit_belong', models.IntegerField(blank=True, help_text='1-7: Would fit in well', null=True)),
                ('po_fit_care', models.IntegerField(blank=True, help_text='1-7: Reflects what I care about', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_ranking', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PostingViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_order', models.IntegerField(help_text='Order this posting was shown (1-6)')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.FloatField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_views', to='core.participant')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.jobposting')),
            ],
            options={
                'ordering': ['participant', 'presentation_order'],
                'unique_together': {('participant', 'posting')},
            },
        ),
        migrations.CreateModel(
            name='Study1Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_order', models.IntegerField(help_text="Position in this participant's sequence (1-indexed)")),
                ('selected_mission_values', models.BooleanField(default=False)),
                ('selected_treats_well', models.BooleanField(default=False)),
                ('selected_pay_benefits', models.BooleanField(default=False)),
                ('selected_job_tasks', models.BooleanField(default=False)),
                ('selected_job_requirements', models.BooleanField(default=False)),
                ('selected_none_unsure', models.BooleanField(default=False)),
                ('displayed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study1_responses', to='core.participant')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.phrase')),
            ],
            options={
                'ordering': ['participant', 'presentation_order'],
                'unique_together': {('participant', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='Study2Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('attractiveness', 'Application Attractiveness'), ('sincerity', 'Perceived Sincerity'), ('employee_treatment', 'Employee Treatment'), ('accept_lower_pay', 'Willingness to Accept Lower Pay'), ('instrumentality', 'Perceived Instrumentality')], max_length=30)),
                ('ranking_order', models.JSONField(help_text='Ordered list of company names, position 0 = rank 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='core.participant')),
            ],
            options={
                'unique_together': {('participant', 'dimension')},
            },
        ),
    ]
