# Generated by Django 5.1.15 on 2026-03-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSortCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(help_text='I1, G1, C1, etc.', max_length=4, unique=True)),
                ('card_type', models.CharField(choices=[('I', 'Identity'), ('G', 'Good-Employer'), ('C', 'Competence')], max_length=1)),
                ('card_text', models.CharField(max_length=300)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='card_sort_posting',
            field=models.ForeignKey(blank=True, help_text='Which posting this participant does the card sort on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_sort_participants', to='core.posting'),
        ),
        migrations.CreateModel(
            name='CardSortResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('card_sort', 'Card Sort'), ('competition', 'Competition')], max_length=15)),
                ('cards_selected', models.JSONField(help_text="List of card_ids selected, e.g. ['I1','C3','G2']")),
                ('selection_order', models.JSONField(blank=True, default=list, help_text='Order in which cards were clicked')),
                ('keep_original', models.BooleanField(default=False, help_text='Competition stage: participant kept original selection')),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sort_responses', to='core.participant')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sort_responses', to='core.posting')),
            ],
            options={
                'unique_together': {('participant', 'stage')},
            },
        ),
    ]
