# Generated by Django 5.1.15 on 2026-03-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardsortcard_participant_card_sort_posting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringManagerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(help_text='HP1, HG1, HW1, HT1, etc.', max_length=4, unique=True)),
                ('card_type', models.CharField(choices=[('P', 'Purpose'), ('G', 'Good-Employer'), ('W', 'Wage'), ('T', 'Task')], max_length=1)),
                ('card_text', models.CharField(max_length=300)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HiringManagerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('card_sort', 'Card Sort'), ('competition', 'Competition')], max_length=15)),
                ('cards_selected', models.JSONField(help_text='card_sort: list of 3 card_ids; competition: list of 0-1 card_ids')),
                ('selection_order', models.JSONField(blank=True, default=list, help_text='Order in which cards were clicked')),
                ('would_change', models.BooleanField(blank=True, help_text='Competition stage: did the participant choose to change? (yes/no)', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hm_responses', to='core.participant')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hm_responses', to='core.posting')),
            ],
            options={
                'unique_together': {('participant', 'stage')},
            },
        ),
    ]
