# Generated by Django 5.1.15 on 2026-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_hiringmanagercard_hiringmanagerresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demographics",
            name="education",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="employment_other",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="gender_self_describe",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="industry_other",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="last_job_search",
        ),
        migrations.RemoveField(
            model_name="demographics",
            name="work_experience_years",
        ),
        migrations.AddField(
            model_name="demographics",
            name="english_first_language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="demographics",
            name="first_language",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="demographics",
            name="gender_other",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="demographics",
            name="has_part_time_job",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="demographics",
            name="high_school_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="demographics",
            name="major",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="demographics",
            name="major_other",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="demographics",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="demographics",
            name="parents_income",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="demographics",
            name="race",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="demographics",
            name="race_other",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="demographics",
            name="year_in_program",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
