# Generated by Django 5.1.15 on 2026-03-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_demographics_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingresponse",
            name="response_time_seconds",
            field=models.FloatField(
                blank=True, help_text="Seconds from page load to submit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rankingresponse",
            name="dimension",
            field=models.CharField(
                choices=[
                    ("perceived_pay", "Perceived Pay"),
                    ("mission_identity", "Mission/Identity Clarity"),
                    ("belief_alignment", "Belief-Work Alignment"),
                    ("employer_quality", "Employer Quality"),
                    ("overall_desirability", "Overall Desirability"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="rankingresponse",
            name="dimension_order",
            field=models.IntegerField(help_text="Presentation order (1-5)"),
        ),
    ]
