# Generated by Django 5.1.15 on 2026-03-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rankingresponse_response_time_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='wage_counterbalance',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='salary_high_high',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='salary_high_low',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='salary_high_text',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='salary_low_high',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='salary_low_low',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='salary_low_text',
        ),
    ]
