# Generated by Django 5.1.15 on 2026-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_participant_wage_counterbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_id',
            field=models.CharField(db_index=True, default='', help_text='User-entered ID — each ID can only be used once', max_length=64, unique=True),
        ),
    ]
