# Generated by Django 5.1.15 on 2026-03-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_job', models.TextField(blank=True)),
                ('weight_matters_to_me', models.IntegerField(blank=True, null=True)),
                ('weight_not_worse', models.IntegerField(blank=True, null=True)),
                ('weight_outside_work', models.IntegerField(blank=True, null=True)),
                ('weight_talented_people', models.IntegerField(blank=True, null=True)),
                ('weight_successful_company', models.IntegerField(blank=True, null=True)),
                ('income_growing_up_percentile', models.IntegerField(blank=True, help_text='Percentile on 2010 CPS distribution', null=True)),
                ('income_future_year', models.CharField(blank=True, help_text='Which distribution year selected: 1970, 1990, or 2019', max_length=4)),
                ('income_future_percentile', models.IntegerField(blank=True, help_text='Percentile on selected distribution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_questions', to='core.participant')),
            ],
        ),
    ]
